### PR TITLE
Fix showing only one container in summary view

### LINKED ISSUE #83: Resource viewer loads forever for sidecar containers
Example config:

```
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: sidecar
spec:
  selector:
    matchLabels:
      app: sidecar
  replicas: 2
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      volumes:
      - name: shared-logs 
        emptyDir: {}
    
      containers:
      - name: app-container
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"]
    
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log
    
      - name: sidecar-container
        image: nginx:1.16.0
        ports:
          - containerPort: 80
    
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html
```

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
Closes #83

Got bitten by this https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables

Signed-off-by: GuessWhoSamFoo <foos@vmware.com>

### CODE REVIEW

File: internal/modules/overview/printer/pod.go [hunk 1]
```diff
@@ -137,8 +138,9 @@ func PodHandler(ctx context.Context, pod *corev1.Pod, opts Options) (component.C
 
 	var containerItems []ItemDescriptor
 	for _, container := range pod.Spec.Containers {
+		container := container
```
Comment (bryanl) [inline internal/modules/overview/printer/pod.go]:
```go
for i := range pod.Spec.Containers {
  container := pod.Spec.Containers[i]
  // ... 
}

File: internal/modules/overview/printer/pod_test.go [hunk 2]
```diff
@@ -15,23 +15,53 @@ import (
...
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
 
 	"github.com/vmware/octant/internal/conversion"
 	"github.com/vmware/octant/internal/testutil"
+	"github.com/vmware/octant/pkg/plugin"
+	"github.com/vmware/octant/pkg/store"
 	"github.com/vmware/octant/pkg/view/component"
 )
 
+var (
```
Comment (bryanl) [inline internal/modules/overview/printer/pod_test.go]: These globals in tests was a sloppy pattern I introduced. We should clean these up at every opportunity we get. This should be in a test function somewhere.

Comment (GuessWhoSamFoo) [reply internal/modules/overview/printer/pod_test.go]: Cleaned this up a bit more
